function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
  AddTextEntry('FE_THDR_GTAO', '~b~TimanttiRP')
  AddTextEntry('PM_PANE_LEAVE', '~b~Poistu Serveriltä')
  AddTextEntry('PM_PANE_QUIT', '~b~Poistu FiveM')
  AddTextEntry('PM_SCR_MAP', '~b~Kartta')
  AddTextEntry('PM_SCR_GAM', '~b~Peli')
  AddTextEntry('PM_SCR_FRI', '~b~Kaverit')
  AddTextEntry('PM_SCR_STO', '~b~Kauppa')
  AddTextEntry('PM_SCR_ONL', '~b~Online')
  AddTextEntry('PM_SCR_INF', '~b~Logit')
  AddTextEntry('PM_SCR_SET', '~b~Asetukset')
  AddTextEntry('PM_SCR_STA', '~b~Status')
  AddTextEntry('PM_SCR_GAL', '~b~Galleria')
  AddTextEntry('PM_SCR_RPL', '~b~Rockstar Editor')
end)
